name: samjosimovic
favicon: null
layout_spectrum: 0.44805812812410295
typography_spectrum: 0.3770280710887164
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3046866049990058
  lightness: 0.38098305533640087
  saturation: 0.7589004142209888
  rhythmicContrast: 0.41052325279451907
purpose: []
