name: samjosimovic
favicon: null
layout_spectrum: 0.31062
typography_spectrum: 0.95959
title: Sam Josimovic
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f181d'
    - '#0693fd'
    - '#385460'
    - '#708d99'
    - '#1771be'
  brandStrength: 0.3125
  lightness: 0.375
  saturation: 0.7589004142209888
  rhythmicContrast: 0.25
purpose: []
